package	TokenNamepackage	
org	TokenNameIdentifier	 org
.	TokenNameDOT	
apache	TokenNameIdentifier	 apache
.	TokenNameDOT	
lucene	TokenNameIdentifier	 lucene
.	TokenNameDOT	
queryParser	TokenNameIdentifier	 query Parser
.	TokenNameDOT	
ext	TokenNameIdentifier	 ext
;	TokenNameSEMICOLON	
/** * Licensed to the Apache Software Foundation (ASF) under one or more * contributor license agreements. See the NOTICE file distributed with * this work for additional information regarding copyright ownership. * The ASF licenses this file to You under the Apache License, Version 2.0 * (the "License"); you may not use this file except in compliance with * the License. You may obtain a copy of the License at * * http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by applicable law or agreed to in writing, software * distributed under the License is distributed on an "AS IS" BASIS, * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. * See the License for the specific language governing permissions and * limitations under the License. */	TokenNameCOMMENT_JAVADOC	 Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to You under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at * http://www.apache.org/licenses/LICENSE-2.0 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. 
import	TokenNameimport	
org	TokenNameIdentifier	 org
.	TokenNameDOT	
apache	TokenNameIdentifier	 apache
.	TokenNameDOT	
lucene	TokenNameIdentifier	 lucene
.	TokenNameDOT	
queryParser	TokenNameIdentifier	 query Parser
.	TokenNameDOT	
ParseException	TokenNameIdentifier	 Parse Exception
;	TokenNameSEMICOLON	
import	TokenNameimport	
org	TokenNameIdentifier	 org
.	TokenNameDOT	
apache	TokenNameIdentifier	 apache
.	TokenNameDOT	
lucene	TokenNameIdentifier	 lucene
.	TokenNameDOT	
queryParser	TokenNameIdentifier	 query Parser
.	TokenNameDOT	
QueryParser	TokenNameIdentifier	 Query Parser
;	TokenNameSEMICOLON	
import	TokenNameimport	
org	TokenNameIdentifier	 org
.	TokenNameDOT	
apache	TokenNameIdentifier	 apache
.	TokenNameDOT	
lucene	TokenNameIdentifier	 lucene
.	TokenNameDOT	
search	TokenNameIdentifier	 search
.	TokenNameDOT	
Query	TokenNameIdentifier	 Query
;	TokenNameSEMICOLON	
/** * This class represents an extension base class to the Lucene standard * {@link QueryParser}. The {@link QueryParser} is generated by the JavaCC * parser generator. Changing or adding functionality or syntax in the standard * query parser requires changes to the JavaCC source file. To enable extending * the standard query parser without changing the JavaCC sources and re-generate * the parser the {@link ParserExtension} can be customized and plugged into an * instance of {@link ExtendableQueryParser}, a direct subclass of * {@link QueryParser}. * * @see Extensions * @see ExtendableQueryParser */	TokenNameCOMMENT_JAVADOC	 This class represents an extension base class to the Lucene standard {@link QueryParser}. The {@link QueryParser} is generated by the JavaCC parser generator. Changing or adding functionality or syntax in the standard query parser requires changes to the JavaCC source file. To enable extending the standard query parser without changing the JavaCC sources and re-generate the parser the {@link ParserExtension} can be customized and plugged into an instance of {@link ExtendableQueryParser}, a direct subclass of {@link QueryParser}. * @see Extensions @see ExtendableQueryParser 
public	TokenNamepublic	
abstract	TokenNameabstract	
class	TokenNameclass	
ParserExtension	TokenNameIdentifier	 Parser Extension
{	TokenNameLBRACE	
/** * Processes the given {@link ExtensionQuery} and returns a corresponding * {@link Query} instance. Subclasses must either return a {@link Query} * instance or raise a {@link ParseException}. This method must not return * <code>null</code>. * * @param query * the extension query * @return a new query instance * @throws ParseException * if the query can not be parsed. */	TokenNameCOMMENT_JAVADOC	 Processes the given {@link ExtensionQuery} and returns a corresponding {@link Query} instance. Subclasses must either return a {@link Query} instance or raise a {@link ParseException}. This method must not return <code>null</code>. * @param query the extension query @return a new query instance @throws ParseException if the query can not be parsed. 
public	TokenNamepublic	
abstract	TokenNameabstract	
Query	TokenNameIdentifier	 Query
parse	TokenNameIdentifier	 parse
(	TokenNameLPAREN	
final	TokenNamefinal	
ExtensionQuery	TokenNameIdentifier	 Extension Query
query	TokenNameIdentifier	 query
)	TokenNameRPAREN	
throws	TokenNamethrows	
ParseException	TokenNameIdentifier	 Parse Exception
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
