/* * Licensed to the Apache Software Foundation (ASF) under one or more * contributor license agreements. See the NOTICE file distributed with * this work for additional information regarding copyright ownership. * The ASF licenses this file to You under the Apache License, Version 2.0 * (the "License"); you may not use this file except in compliance with * the License. You may obtain a copy of the License at * * http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by applicable law or agreed to in writing, software * distributed under the License is distributed on an "AS IS" BASIS, * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. * See the License for the specific language governing permissions and * limitations under the License. * */	TokenNameCOMMENT_BLOCK	 Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to You under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at * http://www.apache.org/licenses/LICENSE-2.0 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. 
/* * This package is based on the work done by Keiron Liddle, Aftex Software * <keiron@aftexsw.com> to whom the Ant project is very grateful for his * great code. */	TokenNameCOMMENT_BLOCK	 This package is based on the work done by Keiron Liddle, Aftex Software <keiron@aftexsw.com> to whom the Ant project is very grateful for his great code. 
package	TokenNamepackage	
org	TokenNameIdentifier	 org
.	TokenNameDOT	
apache	TokenNameIdentifier	 apache
.	TokenNameDOT	
tools	TokenNameIdentifier	 tools
.	TokenNameDOT	
bzip2	TokenNameIdentifier	 bzip2
;	TokenNameSEMICOLON	
/** * Base class for both the compress and decompress classes. * Holds common arrays, and static data. * <p> * This interface is public for historical purposes. * You should have no need to use it. * </p> */	TokenNameCOMMENT_JAVADOC	 Base class for both the compress and decompress classes. Holds common arrays, and static data. <p> This interface is public for historical purposes. You should have no need to use it. </p> 
public	TokenNamepublic	
interface	TokenNameinterface	
BZip2Constants	TokenNameIdentifier	 B Zip2 Constants
{	TokenNameLBRACE	
int	TokenNameint	
baseBlockSize	TokenNameIdentifier	 base Block Size
=	TokenNameEQUAL	
100000	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
int	TokenNameint	
MAX_ALPHA_SIZE	TokenNameIdentifier	 MAX  ALPHA  SIZE
=	TokenNameEQUAL	
258	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
int	TokenNameint	
MAX_CODE_LEN	TokenNameIdentifier	 MAX  CODE  LEN
=	TokenNameEQUAL	
23	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
int	TokenNameint	
RUNA	TokenNameIdentifier	 RUNA
=	TokenNameEQUAL	
0	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
int	TokenNameint	
RUNB	TokenNameIdentifier	 RUNB
=	TokenNameEQUAL	
1	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
int	TokenNameint	
N_GROUPS	TokenNameIdentifier	 N  GROUPS
=	TokenNameEQUAL	
6	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
int	TokenNameint	
G_SIZE	TokenNameIdentifier	 G  SIZE
=	TokenNameEQUAL	
50	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
int	TokenNameint	
N_ITERS	TokenNameIdentifier	 N  ITERS
=	TokenNameEQUAL	
4	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
int	TokenNameint	
MAX_SELECTORS	TokenNameIdentifier	 MAX  SELECTORS
=	TokenNameEQUAL	
(	TokenNameLPAREN	
2	TokenNameIntegerLiteral	
+	TokenNamePLUS	
(	TokenNameLPAREN	
900000	TokenNameIntegerLiteral	
/	TokenNameDIVIDE	
G_SIZE	TokenNameIdentifier	 G  SIZE
)	TokenNameRPAREN	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
int	TokenNameint	
NUM_OVERSHOOT_BYTES	TokenNameIdentifier	 NUM  OVERSHOOT  BYTES
=	TokenNameEQUAL	
20	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** * This array really shouldn't be here. * Again, for historical purposes it is. * * <p>FIXME: This array should be in a private or package private * location, since it could be modified by malicious code.</p> */	TokenNameCOMMENT_JAVADOC	 This array really shouldn't be here. Again, for historical purposes it is. * <p>FIXME: This array should be in a private or package private location, since it could be modified by malicious code.</p> 
int	TokenNameint	
[	TokenNameLBRACKET	
]	TokenNameRBRACKET	
rNums	TokenNameIdentifier	 r Nums
=	TokenNameEQUAL	
{	TokenNameLBRACE	
619	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
720	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
127	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
481	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
931	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
816	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
813	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
233	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
566	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
247	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
985	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
724	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
205	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
454	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
863	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
491	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
741	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
242	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
949	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
214	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
733	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
859	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
335	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
708	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
621	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
574	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
73	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
654	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
730	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
472	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
419	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
436	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
278	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
496	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
867	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
210	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
399	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
680	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
480	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
51	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
878	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
465	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
811	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
169	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
869	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
675	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
611	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
697	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
867	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
561	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
862	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
687	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
507	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
283	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
482	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
129	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
807	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
591	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
733	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
623	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
150	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
238	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
59	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
379	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
684	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
877	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
625	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
169	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
643	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
105	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
170	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
607	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
520	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
932	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
727	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
476	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
693	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
425	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
174	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
647	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
73	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
122	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
335	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
530	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
442	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
853	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
695	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
249	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
445	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
515	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
909	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
545	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
703	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
919	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
874	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
474	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
882	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
500	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
594	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
612	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
641	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
801	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
220	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
162	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
819	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
984	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
589	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
513	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
495	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
799	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
161	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
604	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
958	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
533	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
221	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
400	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
386	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
867	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
600	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
782	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
382	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
596	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
414	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
171	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
516	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
375	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
682	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
485	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
911	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
276	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
98	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
553	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
163	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
354	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
666	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
933	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
424	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
341	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
533	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
870	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
227	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
730	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
475	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
186	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
263	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
647	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
537	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
686	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
600	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
224	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
469	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
68	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
770	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
919	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
190	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
373	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
294	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
822	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
808	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
206	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
184	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
943	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
795	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
384	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
383	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
461	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
404	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
758	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
839	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
887	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
715	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
67	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
618	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
276	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
204	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
918	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
873	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
777	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
604	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
560	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
951	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
160	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
578	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
722	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
79	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
804	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
96	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
409	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
713	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
940	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
652	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
934	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
970	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
447	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
318	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
353	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
859	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
672	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
112	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
785	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
645	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
863	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
803	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
350	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
139	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
93	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
354	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
99	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
820	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
908	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
609	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
772	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
154	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
274	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
580	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
184	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
79	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
626	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
630	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
742	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
653	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
282	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
762	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
623	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
680	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
81	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
927	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
626	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
789	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
125	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
411	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
521	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
938	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
300	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
821	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
78	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
343	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
175	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
128	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
250	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
170	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
774	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
972	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
275	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
999	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
639	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
495	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
78	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
352	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
126	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
857	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
956	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
358	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
619	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
580	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
124	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
737	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
594	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
701	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
612	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
669	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
112	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
134	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
694	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
363	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
992	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
809	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
743	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
168	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
974	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
944	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
375	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
748	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
52	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
600	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
747	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
642	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
182	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
862	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
81	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
344	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
805	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
988	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
739	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
511	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
655	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
814	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
334	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
249	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
515	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
897	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
955	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
664	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
981	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
649	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
113	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
974	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
459	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
893	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
228	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
433	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
837	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
553	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
268	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
926	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
240	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
102	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
654	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
459	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
51	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
686	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
754	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
806	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
760	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
493	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
403	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
415	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
394	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
687	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
700	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
946	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
670	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
656	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
610	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
738	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
392	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
760	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
799	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
887	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
653	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
978	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
321	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
576	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
617	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
626	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
502	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
894	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
679	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
243	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
440	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
680	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
879	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
194	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
572	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
640	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
724	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
926	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
56	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
204	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
700	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
707	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
151	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
457	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
449	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
797	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
195	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
791	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
558	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
945	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
679	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
297	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
59	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
87	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
824	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
713	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
663	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
412	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
693	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
342	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
606	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
134	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
108	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
571	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
364	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
631	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
212	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
174	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
643	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
304	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
329	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
343	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
97	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
430	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
751	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
497	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
314	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
983	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
374	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
822	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
928	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
140	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
206	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
73	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
263	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
980	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
736	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
876	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
478	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
430	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
305	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
170	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
514	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
364	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
692	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
829	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
82	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
855	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
953	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
676	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
246	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
369	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
970	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
294	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
750	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
807	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
827	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
150	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
790	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
288	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
923	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
804	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
378	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
215	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
828	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
592	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
281	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
565	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
555	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
710	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
82	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
896	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
831	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
547	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
261	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
524	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
462	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
293	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
465	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
502	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
56	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
661	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
821	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
976	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
991	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
658	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
869	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
905	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
758	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
745	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
193	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
768	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
550	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
608	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
933	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
378	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
286	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
215	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
979	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
792	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
961	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
61	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
688	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
793	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
644	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
986	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
403	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
106	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
366	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
905	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
644	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
372	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
567	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
466	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
434	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
645	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
210	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
389	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
550	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
919	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
135	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
780	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
773	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
635	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
389	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
707	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
100	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
626	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
958	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
165	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
504	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
920	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
176	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
193	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
713	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
857	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
265	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
203	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
50	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
668	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
108	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
645	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
990	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
626	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
197	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
510	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
357	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
358	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
850	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
858	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
364	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
936	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
638	TokenNameIntegerLiteral	
}	TokenNameRBRACE	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
