/* * Licensed to the Apache Software Foundation (ASF) under one or more * contributor license agreements. See the NOTICE file distributed with * this work for additional information regarding copyright ownership. * The ASF licenses this file to You under the Apache License, Version 2.0 * (the "License"); you may not use this file except in compliance with * the License. You may obtain a copy of the License at * * http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by applicable law or agreed to in writing, software * distributed under the License is distributed on an "AS IS" BASIS, * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. * See the License for the specific language governing permissions and * limitations under the License. * */	TokenNameCOMMENT_BLOCK	 Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to You under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at * http://www.apache.org/licenses/LICENSE-2.0 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. 
/* * This package is based on the work done by Keiron Liddle, Aftex Software * <keiron@aftexsw.com> to whom the Ant project is very grateful for his * great code. */	TokenNameCOMMENT_BLOCK	 This package is based on the work done by Keiron Liddle, Aftex Software <keiron@aftexsw.com> to whom the Ant project is very grateful for his great code. 
package	TokenNamepackage	
org	TokenNameIdentifier	 org
.	TokenNameDOT	
apache	TokenNameIdentifier	 apache
.	TokenNameDOT	
tools	TokenNameIdentifier	 tools
.	TokenNameDOT	
bzip2	TokenNameIdentifier	 bzip2
;	TokenNameSEMICOLON	
/** * A simple class the hold and calculate the CRC for sanity checking * of the data. * */	TokenNameCOMMENT_JAVADOC	 A simple class the hold and calculate the CRC for sanity checking of the data. 
final	TokenNamefinal	
class	TokenNameclass	
CRC	TokenNameIdentifier	 CRC
{	TokenNameLBRACE	
static	TokenNamestatic	
final	TokenNamefinal	
int	TokenNameint	
crc32Table	TokenNameIdentifier	 crc32 Table
[	TokenNameLBRACKET	
]	TokenNameRBRACKET	
=	TokenNameEQUAL	
{	TokenNameLBRACE	
0x00000000	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x04c11db7	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x09823b6e	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x0d4326d9	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x130476dc	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x17c56b6b	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x1a864db2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x1e475005	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x2608edb8	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x22c9f00f	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x2f8ad6d6	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x2b4bcb61	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x350c9b64	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x31cd86d3	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x3c8ea00a	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x384fbdbd	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x4c11db70	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x48d0c6c7	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x4593e01e	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x4152fda9	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x5f15adac	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x5bd4b01b	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x569796c2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x52568b75	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x6a1936c8	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x6ed82b7f	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x639b0da6	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x675a1011	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x791d4014	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x7ddc5da3	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x709f7b7a	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x745e66cd	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x9823b6e0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x9ce2ab57	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x91a18d8e	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x95609039	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x8b27c03c	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x8fe6dd8b	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x82a5fb52	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x8664e6e5	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xbe2b5b58	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xbaea46ef	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xb7a96036	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xb3687d81	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xad2f2d84	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xa9ee3033	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xa4ad16ea	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xa06c0b5d	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xd4326d90	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xd0f37027	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xddb056fe	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xd9714b49	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xc7361b4c	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xc3f706fb	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xceb42022	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xca753d95	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xf23a8028	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xf6fb9d9f	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xfbb8bb46	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xff79a6f1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xe13ef6f4	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xe5ffeb43	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xe8bccd9a	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xec7dd02d	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x34867077	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x30476dc0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x3d044b19	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x39c556ae	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x278206ab	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x23431b1c	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x2e003dc5	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x2ac12072	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x128e9dcf	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x164f8078	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x1b0ca6a1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x1fcdbb16	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x018aeb13	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x054bf6a4	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x0808d07d	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x0cc9cdca	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x7897ab07	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x7c56b6b0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x71159069	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x75d48dde	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x6b93dddb	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x6f52c06c	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x6211e6b5	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x66d0fb02	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x5e9f46bf	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x5a5e5b08	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x571d7dd1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x53dc6066	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x4d9b3063	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x495a2dd4	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x44190b0d	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x40d816ba	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xaca5c697	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xa864db20	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xa527fdf9	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xa1e6e04e	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xbfa1b04b	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xbb60adfc	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xb6238b25	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xb2e29692	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x8aad2b2f	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x8e6c3698	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x832f1041	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x87ee0df6	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x99a95df3	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x9d684044	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x902b669d	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x94ea7b2a	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xe0b41de7	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xe4750050	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xe9362689	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xedf73b3e	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xf3b06b3b	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xf771768c	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xfa325055	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xfef34de2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xc6bcf05f	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xc27dede8	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xcf3ecb31	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xcbffd686	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xd5b88683	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xd1799b34	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xdc3abded	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xd8fba05a	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x690ce0ee	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x6dcdfd59	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x608edb80	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x644fc637	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x7a089632	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x7ec98b85	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x738aad5c	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x774bb0eb	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x4f040d56	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x4bc510e1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x46863638	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x42472b8f	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x5c007b8a	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x58c1663d	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x558240e4	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x51435d53	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x251d3b9e	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x21dc2629	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x2c9f00f0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x285e1d47	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x36194d42	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x32d850f5	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x3f9b762c	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x3b5a6b9b	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x0315d626	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x07d4cb91	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x0a97ed48	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x0e56f0ff	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x1011a0fa	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x14d0bd4d	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x19939b94	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x1d528623	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xf12f560e	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xf5ee4bb9	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xf8ad6d60	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xfc6c70d7	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xe22b20d2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xe6ea3d65	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xeba91bbc	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xef68060b	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xd727bbb6	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xd3e6a601	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xdea580d8	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xda649d6f	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xc423cd6a	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xc0e2d0dd	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xcda1f604	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xc960ebb3	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xbd3e8d7e	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xb9ff90c9	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xb4bcb610	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xb07daba7	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xae3afba2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xaafbe615	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xa7b8c0cc	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xa379dd7b	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x9b3660c6	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x9ff77d71	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x92b45ba8	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x9675461f	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x8832161a	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x8cf30bad	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x81b02d74	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x857130c3	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x5d8a9099	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x594b8d2e	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x5408abf7	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x50c9b640	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x4e8ee645	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x4a4ffbf2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x470cdd2b	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x43cdc09c	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x7b827d21	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x7f436096	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x7200464f	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x76c15bf8	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x68860bfd	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x6c47164a	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x61043093	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x65c52d24	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x119b4be9	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x155a565e	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x18197087	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x1cd86d30	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x029f3d35	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x065e2082	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x0b1d065b	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x0fdc1bec	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x3793a651	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x3352bbe6	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x3e119d3f	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x3ad08088	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x2497d08d	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x2056cd3a	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x2d15ebe3	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x29d4f654	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xc5a92679	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xc1683bce	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xcc2b1d17	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xc8ea00a0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xd6ad50a5	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xd26c4d12	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xdf2f6bcb	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xdbee767c	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xe3a1cbc1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xe760d676	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xea23f0af	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xeee2ed18	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xf0a5bd1d	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xf464a0aa	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xf9278673	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xfde69bc4	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x89b8fd09	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x8d79e0be	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x803ac667	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x84fbdbd0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x9abc8bd5	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x9e7d9662	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x933eb0bb	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0x97ffad0c	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xafb010b1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xab710d06	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xa6322bdf	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xa2f33668	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xbcb4666d	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xb8757bda	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xb5365d03	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0xb1f740b4	TokenNameIntegerLiteral	
}	TokenNameRBRACE	
;	TokenNameSEMICOLON	
CRC	TokenNameIdentifier	 CRC
(	TokenNameLPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
initialiseCRC	TokenNameIdentifier	 initialise CRC
(	TokenNameLPAREN	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
void	TokenNamevoid	
initialiseCRC	TokenNameIdentifier	 initialise CRC
(	TokenNameLPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
globalCrc	TokenNameIdentifier	 global Crc
=	TokenNameEQUAL	
0xffffffff	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
int	TokenNameint	
getFinalCRC	TokenNameIdentifier	 get Final CRC
(	TokenNameLPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
return	TokenNamereturn	
~	TokenNameTWIDDLE	
globalCrc	TokenNameIdentifier	 global Crc
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
int	TokenNameint	
getGlobalCRC	TokenNameIdentifier	 get Global CRC
(	TokenNameLPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
return	TokenNamereturn	
globalCrc	TokenNameIdentifier	 global Crc
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
void	TokenNamevoid	
setGlobalCRC	TokenNameIdentifier	 set Global CRC
(	TokenNameLPAREN	
int	TokenNameint	
newCrc	TokenNameIdentifier	 new Crc
)	TokenNameRPAREN	
{	TokenNameLBRACE	
globalCrc	TokenNameIdentifier	 global Crc
=	TokenNameEQUAL	
newCrc	TokenNameIdentifier	 new Crc
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
void	TokenNamevoid	
updateCRC	TokenNameIdentifier	 update CRC
(	TokenNameLPAREN	
int	TokenNameint	
inCh	TokenNameIdentifier	 in Ch
)	TokenNameRPAREN	
{	TokenNameLBRACE	
int	TokenNameint	
temp	TokenNameIdentifier	 temp
=	TokenNameEQUAL	
(	TokenNameLPAREN	
globalCrc	TokenNameIdentifier	 global Crc
>>	TokenNameRIGHT_SHIFT	
24	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
^	TokenNameXOR	
inCh	TokenNameIdentifier	 in Ch
;	TokenNameSEMICOLON	
if	TokenNameif	
(	TokenNameLPAREN	
temp	TokenNameIdentifier	 temp
<	TokenNameLESS	
0	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
temp	TokenNameIdentifier	 temp
=	TokenNameEQUAL	
256	TokenNameIntegerLiteral	
+	TokenNamePLUS	
temp	TokenNameIdentifier	 temp
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
globalCrc	TokenNameIdentifier	 global Crc
=	TokenNameEQUAL	
(	TokenNameLPAREN	
globalCrc	TokenNameIdentifier	 global Crc
<<	TokenNameLEFT_SHIFT	
8	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
^	TokenNameXOR	
CRC	TokenNameIdentifier	 CRC
.	TokenNameDOT	
crc32Table	TokenNameIdentifier	 crc32 Table
[	TokenNameLBRACKET	
temp	TokenNameIdentifier	 temp
]	TokenNameRBRACKET	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
void	TokenNamevoid	
updateCRC	TokenNameIdentifier	 update CRC
(	TokenNameLPAREN	
int	TokenNameint	
inCh	TokenNameIdentifier	 in Ch
,	TokenNameCOMMA	
int	TokenNameint	
repeat	TokenNameIdentifier	 repeat
)	TokenNameRPAREN	
{	TokenNameLBRACE	
int	TokenNameint	
globalCrcShadow	TokenNameIdentifier	 global Crc Shadow
=	TokenNameEQUAL	
this	TokenNamethis	
.	TokenNameDOT	
globalCrc	TokenNameIdentifier	 global Crc
;	TokenNameSEMICOLON	
while	TokenNamewhile	
(	TokenNameLPAREN	
repeat	TokenNameIdentifier	 repeat
--	TokenNameMINUS_MINUS	
>	TokenNameGREATER	
0	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
int	TokenNameint	
temp	TokenNameIdentifier	 temp
=	TokenNameEQUAL	
(	TokenNameLPAREN	
globalCrcShadow	TokenNameIdentifier	 global Crc Shadow
>>	TokenNameRIGHT_SHIFT	
24	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
^	TokenNameXOR	
inCh	TokenNameIdentifier	 in Ch
;	TokenNameSEMICOLON	
globalCrcShadow	TokenNameIdentifier	 global Crc Shadow
=	TokenNameEQUAL	
(	TokenNameLPAREN	
globalCrcShadow	TokenNameIdentifier	 global Crc Shadow
<<	TokenNameLEFT_SHIFT	
8	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
^	TokenNameXOR	
crc32Table	TokenNameIdentifier	 crc32 Table
[	TokenNameLBRACKET	
(	TokenNameLPAREN	
temp	TokenNameIdentifier	 temp
>=	TokenNameGREATER_EQUAL	
0	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
?	TokenNameQUESTION	
temp	TokenNameIdentifier	 temp
:	TokenNameCOLON	
(	TokenNameLPAREN	
temp	TokenNameIdentifier	 temp
+	TokenNamePLUS	
256	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
]	TokenNameRBRACKET	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
this	TokenNamethis	
.	TokenNameDOT	
globalCrc	TokenNameIdentifier	 global Crc
=	TokenNameEQUAL	
globalCrcShadow	TokenNameIdentifier	 global Crc Shadow
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
int	TokenNameint	
globalCrc	TokenNameIdentifier	 global Crc
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
