/* * Copyright (c) 2006 World Wide Web Consortium, * * (Massachusetts Institute of Technology, European Research Consortium for * Informatics and Mathematics, Keio University). All Rights Reserved. This * work is distributed under the W3C(r) Software License [1] in the hope that * it will be useful, but WITHOUT ANY WARRANTY; without even the implied * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. * * [1] http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231 */	TokenNameCOMMENT_BLOCK	 Copyright (c) 2006 World Wide Web Consortium, * (Massachusetts Institute of Technology, European Research Consortium for Informatics and Mathematics, Keio University). All Rights Reserved. This work is distributed under the W3C(r) Software License [1] in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. * [1] http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231 
package	TokenNamepackage	
org	TokenNameIdentifier	 org
.	TokenNameDOT	
w3c	TokenNameIdentifier	 w3c
.	TokenNameDOT	
dom	TokenNameIdentifier	 dom
.	TokenNameDOT	
events	TokenNameIdentifier	 events
;	TokenNameSEMICOLON	
import	TokenNameimport	
org	TokenNameIdentifier	 org
.	TokenNameDOT	
w3c	TokenNameIdentifier	 w3c
.	TokenNameDOT	
dom	TokenNameIdentifier	 dom
.	TokenNameDOT	
views	TokenNameIdentifier	 views
.	TokenNameDOT	
AbstractView	TokenNameIdentifier	 Abstract View
;	TokenNameSEMICOLON	
/** * The <code>TextEvent</code> interface provides specific contextual * information associated with Text Events. * <p> To create an instance of the <code>TextEvent</code> interface, use the * <code>DocumentEvent.createEvent("TextEvent")</code> method call. * <p>See also the <a href='http://www.w3.org/TR/2006/WD-DOM-Level-3-Events-20060413'> Document Object Model (DOM) Level 3 Events Specification </a>. * @since DOM Level 3 */	TokenNameCOMMENT_JAVADOC	 The <code>TextEvent</code> interface provides specific contextual information associated with Text Events. <p> To create an instance of the <code>TextEvent</code> interface, use the <code>DocumentEvent.createEvent("TextEvent")</code> method call. <p>See also the <a href='http://www.w3.org/TR/2006/WD-DOM-Level-3-Events-20060413'> Document Object Model (DOM) Level 3 Events Specification </a>. @since DOM Level 3 
public	TokenNamepublic	
interface	TokenNameinterface	
TextEvent	TokenNameIdentifier	 Text Event
extends	TokenNameextends	
UIEvent	TokenNameIdentifier	 UI Event
{	TokenNameLBRACE	
/** * <code>data</code> holds the value of the characters generated by the * character device. This may be a single Unicode character or a * non-empty sequence of Unicode characters [Unicode]. Characters should be normalized as defined by the Unicode * normalization form NFC, defined in [<a href='http://www.unicode.org/reports/tr15/'>UAX #15</a>]. This attribute * cannot be null or contain the empty string. */	TokenNameCOMMENT_JAVADOC	 <code>data</code> holds the value of the characters generated by the character device. This may be a single Unicode character or a non-empty sequence of Unicode characters [Unicode]. Characters should be normalized as defined by the Unicode normalization form NFC, defined in [<a href='http://www.unicode.org/reports/tr15/'>UAX #15</a>]. This attribute cannot be null or contain the empty string. 
public	TokenNamepublic	
String	TokenNameIdentifier	 String
getData	TokenNameIdentifier	 get Data
(	TokenNameLPAREN	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
/** * The <code>initTextEvent</code> method is used to initialize the value * of a <code>TextEvent</code> object and has the same behavior as * <code>UIEvent.initUIEvent()</code>. The value of * <code>UIEvent.detail</code> remains undefined. * @param typeArg Refer to the <code>UIEvent.initUIEvent()</code> method * for a description of this parameter. * @param canBubbleArg Refer to the <code>UIEvent.initUIEvent()</code> * method for a description of this parameter. * @param cancelableArg Refer to the <code>UIEvent.initUIEvent()</code> * method for a description of this parameter. * @param viewArg Refer to the <code>UIEvent.initUIEvent()</code> method * for a description of this parameter. * @param dataArg Specifies <code>TextEvent.data</code>. */	TokenNameCOMMENT_JAVADOC	 The <code>initTextEvent</code> method is used to initialize the value of a <code>TextEvent</code> object and has the same behavior as <code>UIEvent.initUIEvent()</code>. The value of <code>UIEvent.detail</code> remains undefined. @param typeArg Refer to the <code>UIEvent.initUIEvent()</code> method for a description of this parameter. @param canBubbleArg Refer to the <code>UIEvent.initUIEvent()</code> method for a description of this parameter. @param cancelableArg Refer to the <code>UIEvent.initUIEvent()</code> method for a description of this parameter. @param viewArg Refer to the <code>UIEvent.initUIEvent()</code> method for a description of this parameter. @param dataArg Specifies <code>TextEvent.data</code>. 
public	TokenNamepublic	
void	TokenNamevoid	
initTextEvent	TokenNameIdentifier	 init Text Event
(	TokenNameLPAREN	
String	TokenNameIdentifier	 String
typeArg	TokenNameIdentifier	 type Arg
,	TokenNameCOMMA	
boolean	TokenNameboolean	
canBubbleArg	TokenNameIdentifier	 can Bubble Arg
,	TokenNameCOMMA	
boolean	TokenNameboolean	
cancelableArg	TokenNameIdentifier	 cancelable Arg
,	TokenNameCOMMA	
AbstractView	TokenNameIdentifier	 Abstract View
viewArg	TokenNameIdentifier	 view Arg
,	TokenNameCOMMA	
String	TokenNameIdentifier	 String
dataArg	TokenNameIdentifier	 data Arg
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
/** * The <code>initTextEventNS</code> method is used to initialize the * value of a <code>TextEvent</code> object and has the same behavior as * <code>UIEvent.initUIEventNS()</code>. The value of * <code>UIEvent.detail</code> remains undefined. * @param namespaceURI Refer to the <code>UIEvent.initUIEventNS()</code> * method for a description of this parameter. * @param type Refer to the <code>UIEvent.initUIEventNS()</code> method * for a description of this parameter. * @param canBubbleArg Refer to the <code>UIEvent.initUIEventNS()</code> * method for a description of this parameter. * @param cancelableArg Refer to the <code>UIEvent.initUIEventNS()</code> * method for a description of this parameter. * @param viewArg Refer to the <code>UIEvent.initUIEventNS()</code> * method for a description of this parameter. * @param dataArg Refer to the <code>TextEvent.initTextEvent()</code> * method for a description of this parameter. */	TokenNameCOMMENT_JAVADOC	 The <code>initTextEventNS</code> method is used to initialize the value of a <code>TextEvent</code> object and has the same behavior as <code>UIEvent.initUIEventNS()</code>. The value of <code>UIEvent.detail</code> remains undefined. @param namespaceURI Refer to the <code>UIEvent.initUIEventNS()</code> method for a description of this parameter. @param type Refer to the <code>UIEvent.initUIEventNS()</code> method for a description of this parameter. @param canBubbleArg Refer to the <code>UIEvent.initUIEventNS()</code> method for a description of this parameter. @param cancelableArg Refer to the <code>UIEvent.initUIEventNS()</code> method for a description of this parameter. @param viewArg Refer to the <code>UIEvent.initUIEventNS()</code> method for a description of this parameter. @param dataArg Refer to the <code>TextEvent.initTextEvent()</code> method for a description of this parameter. 
public	TokenNamepublic	
void	TokenNamevoid	
initTextEventNS	TokenNameIdentifier	 init Text Event NS
(	TokenNameLPAREN	
String	TokenNameIdentifier	 String
namespaceURI	TokenNameIdentifier	 namespace URI
,	TokenNameCOMMA	
String	TokenNameIdentifier	 String
type	TokenNameIdentifier	 type
,	TokenNameCOMMA	
boolean	TokenNameboolean	
canBubbleArg	TokenNameIdentifier	 can Bubble Arg
,	TokenNameCOMMA	
boolean	TokenNameboolean	
cancelableArg	TokenNameIdentifier	 cancelable Arg
,	TokenNameCOMMA	
AbstractView	TokenNameIdentifier	 Abstract View
viewArg	TokenNameIdentifier	 view Arg
,	TokenNameCOMMA	
String	TokenNameIdentifier	 String
dataArg	TokenNameIdentifier	 data Arg
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
