/* Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to You under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. */	TokenNameCOMMENT_BLOCK	 Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to You under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. 
package	TokenNamepackage	
org	TokenNameIdentifier	 org
.	TokenNameDOT	
apache	TokenNameIdentifier	 apache
.	TokenNameDOT	
batik	TokenNameIdentifier	 batik
.	TokenNameDOT	
svggen	TokenNameIdentifier	 svggen
;	TokenNameSEMICOLON	
import	TokenNameimport	
java	TokenNameIdentifier	 java
.	TokenNameDOT	
util	TokenNameIdentifier	 util
.	TokenNameDOT	
HashMap	TokenNameIdentifier	 Hash Map
;	TokenNameSEMICOLON	
import	TokenNameimport	
java	TokenNameIdentifier	 java
.	TokenNameDOT	
util	TokenNameIdentifier	 util
.	TokenNameDOT	
LinkedList	TokenNameIdentifier	 Linked List
;	TokenNameSEMICOLON	
import	TokenNameimport	
java	TokenNameIdentifier	 java
.	TokenNameDOT	
util	TokenNameIdentifier	 util
.	TokenNameDOT	
List	TokenNameIdentifier	 List
;	TokenNameSEMICOLON	
import	TokenNameimport	
java	TokenNameIdentifier	 java
.	TokenNameDOT	
util	TokenNameIdentifier	 util
.	TokenNameDOT	
Map	TokenNameIdentifier	 Map
;	TokenNameSEMICOLON	
/** * Abstract class with common utility methods used by subclasses * for specific convertion operations. It holds a reference to a * domFactory Document, which many implementations use, and provides * a convenience method, to offers a convertion of double values * to String that remove the trailing '.' character on integral * values. * * @author <a href="mailto:vincent.hardy@eng.sun.com">Vincent Hardy</a> * @version $Id: AbstractSVGConverter.java 475477 2006-11-15 22:44:28Z cam $ */	TokenNameCOMMENT_JAVADOC	 Abstract class with common utility methods used by subclasses for specific convertion operations. It holds a reference to a domFactory Document, which many implementations use, and provides a convenience method, to offers a convertion of double values to String that remove the trailing '.' character on integral values. * @author <a href="mailto:vincent.hardy@eng.sun.com">Vincent Hardy</a> @version $Id: AbstractSVGConverter.java 475477 2006-11-15 22:44:28Z cam $ 
public	TokenNamepublic	
abstract	TokenNameabstract	
class	TokenNameclass	
AbstractSVGConverter	TokenNameIdentifier	 Abstract SVG Converter
implements	TokenNameimplements	
SVGConverter	TokenNameIdentifier	 SVG Converter
,	TokenNameCOMMA	
ErrorConstants	TokenNameIdentifier	 Error Constants
{	TokenNameLBRACE	
/** * Used by converters to create Elements and other DOM objects */	TokenNameCOMMENT_JAVADOC	 Used by converters to create Elements and other DOM objects 
protected	TokenNameprotected	
SVGGeneratorContext	TokenNameIdentifier	 SVG Generator Context
generatorContext	TokenNameIdentifier	 generator Context
;	TokenNameSEMICOLON	
/** * Map of descriptions already processed by this converter. The * key type is left to the implementations */	TokenNameCOMMENT_JAVADOC	 Map of descriptions already processed by this converter. The key type is left to the implementations 
protected	TokenNameprotected	
Map	TokenNameIdentifier	 Map
descMap	TokenNameIdentifier	 desc Map
=	TokenNameEQUAL	
new	TokenNamenew	
HashMap	TokenNameIdentifier	 Hash Map
(	TokenNameLPAREN	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
/** * Set of definitions to interpret the values of the attributes * generated by this converter since its creation */	TokenNameCOMMENT_JAVADOC	 Set of definitions to interpret the values of the attributes generated by this converter since its creation 
protected	TokenNameprotected	
List	TokenNameIdentifier	 List
defSet	TokenNameIdentifier	 def Set
=	TokenNameEQUAL	
new	TokenNamenew	
LinkedList	TokenNameIdentifier	 Linked List
(	TokenNameLPAREN	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
/** * @param generatorContext can be used by the SVGConverter extensions * to create Elements and other types of DOM objects. */	TokenNameCOMMENT_JAVADOC	 @param generatorContext can be used by the SVGConverter extensions to create Elements and other types of DOM objects. 
public	TokenNamepublic	
AbstractSVGConverter	TokenNameIdentifier	 Abstract SVG Converter
(	TokenNameLPAREN	
SVGGeneratorContext	TokenNameIdentifier	 SVG Generator Context
generatorContext	TokenNameIdentifier	 generator Context
)	TokenNameRPAREN	
{	TokenNameLBRACE	
if	TokenNameif	
(	TokenNameLPAREN	
generatorContext	TokenNameIdentifier	 generator Context
==	TokenNameEQUAL_EQUAL	
null	TokenNamenull	
)	TokenNameRPAREN	
throw	TokenNamethrow	
new	TokenNamenew	
SVGGraphics2DRuntimeException	TokenNameIdentifier	 SVG Graphics2 D Runtime Exception
(	TokenNameLPAREN	
ERR_CONTEXT_NULL	TokenNameIdentifier	 ERR  CONTEXT  NULL
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
this	TokenNamethis	
.	TokenNameDOT	
generatorContext	TokenNameIdentifier	 generator Context
=	TokenNameEQUAL	
generatorContext	TokenNameIdentifier	 generator Context
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
/** * @return set of definitions referenced by the attribute * values created by the implementation since its * creation. The return value should never be null. * If no definition is needed, an empty set should be * returned. */	TokenNameCOMMENT_JAVADOC	 @return set of definitions referenced by the attribute values created by the implementation since its creation. The return value should never be null. If no definition is needed, an empty set should be returned. 
public	TokenNamepublic	
List	TokenNameIdentifier	 List
getDefinitionSet	TokenNameIdentifier	 get Definition Set
(	TokenNameLPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
return	TokenNamereturn	
defSet	TokenNameIdentifier	 def Set
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
/** * Utility method for subclasses. */	TokenNameCOMMENT_JAVADOC	 Utility method for subclasses. 
public	TokenNamepublic	
final	TokenNamefinal	
String	TokenNameIdentifier	 String
doubleString	TokenNameIdentifier	 double String
(	TokenNameLPAREN	
double	TokenNamedouble	
value	TokenNameIdentifier	 value
)	TokenNameRPAREN	
{	TokenNameLBRACE	
return	TokenNamereturn	
generatorContext	TokenNameIdentifier	 generator Context
.	TokenNameDOT	
doubleString	TokenNameIdentifier	 double String
(	TokenNameLPAREN	
value	TokenNameIdentifier	 value
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
}	TokenNameRBRACE	
