/* * Licensed to the Apache Software Foundation (ASF) under one or more * contributor license agreements. See the NOTICE file distributed with * this work for additional information regarding copyright ownership. * The ASF licenses this file to You under the Apache License, Version 2.0 * (the "License"); you may not use this file except in compliance with * the License. You may obtain a copy of the License at * * http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by applicable law or agreed to in writing, software * distributed under the License is distributed on an "AS IS" BASIS, * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. * See the License for the specific language governing permissions and * limitations under the License. */	TokenNameCOMMENT_BLOCK	 Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to You under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at * http://www.apache.org/licenses/LICENSE-2.0 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. 
package	TokenNamepackage	
org	TokenNameIdentifier	 org
.	TokenNameDOT	
apache	TokenNameIdentifier	 apache
.	TokenNameDOT	
log4j	TokenNameIdentifier	 log4j
.	TokenNameDOT	
helpers	TokenNameIdentifier	 helpers
;	TokenNameSEMICOLON	
/** SingleLineTracerPrintWriter overrides the println function in TracerPrintWriter by replacing the TAB character with spaces. It also does not print the "\n". <p> The default format generated by TracerPrintWriter for exceptions prints on multiple lines, which does not interact well with some logging systems. On the other hand, a stack-trace on one line can be a mite difficult to read, so this class should only be used where really necessary :-) <p> For syslog daemons, tabs in messages are not friendly, hence the replacement of tabs by spaces here. It shouldn't do any harm to do this for all messages... <p> Perhaps it might be better to enhance TracerPrintWriter to have a configuration item for one-line or multi-line mode... */	TokenNameCOMMENT_JAVADOC	 SingleLineTracerPrintWriter overrides the println function in TracerPrintWriter by replacing the TAB character with spaces. It also does not print the "\n". <p> The default format generated by TracerPrintWriter for exceptions prints on multiple lines, which does not interact well with some logging systems. On the other hand, a stack-trace on one line can be a mite difficult to read, so this class should only be used where really necessary :-) <p> For syslog daemons, tabs in messages are not friendly, hence the replacement of tabs by spaces here. It shouldn't do any harm to do this for all messages... <p> Perhaps it might be better to enhance TracerPrintWriter to have a configuration item for one-line or multi-line mode... 
public	TokenNamepublic	
class	TokenNameclass	
SingleLineTracerPrintWriter	TokenNameIdentifier	 Single Line Tracer Print Writer
extends	TokenNameextends	
TracerPrintWriter	TokenNameIdentifier	 Tracer Print Writer
{	TokenNameLBRACE	
static	TokenNamestatic	
String	TokenNameIdentifier	 String
TAB	TokenNameIdentifier	 TAB
=	TokenNameEQUAL	
" "	TokenNameStringLiteral	 
;	TokenNameSEMICOLON	
public	TokenNamepublic	
SingleLineTracerPrintWriter	TokenNameIdentifier	 Single Line Tracer Print Writer
(	TokenNameLPAREN	
QuietWriter	TokenNameIdentifier	 Quiet Writer
qWriter	TokenNameIdentifier	 q Writer
)	TokenNameRPAREN	
{	TokenNameLBRACE	
super	TokenNamesuper	
(	TokenNameLPAREN	
qWriter	TokenNameIdentifier	 q Writer
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
/** Make the first Exception line print properly by omitting the \n at the end. */	TokenNameCOMMENT_JAVADOC	 Make the first Exception line print properly by omitting the \n at the end. 
public	TokenNamepublic	
void	TokenNamevoid	
println	TokenNameIdentifier	 println
(	TokenNameLPAREN	
Object	TokenNameIdentifier	 Object
o	TokenNameIdentifier	 o
)	TokenNameRPAREN	
{	TokenNameLBRACE	
this	TokenNamethis	
.	TokenNameDOT	
qWriter	TokenNameIdentifier	 q Writer
.	TokenNameDOT	
write	TokenNameIdentifier	 write
(	TokenNameLPAREN	
o	TokenNameIdentifier	 o
.	TokenNameDOT	
toString	TokenNameIdentifier	 to String
(	TokenNameLPAREN	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
// Note: the Char[] form is handled by the TracerPrinterWriter super 	TokenNameCOMMENT_LINE	Note: the Char[] form is handled by the TracerPrinterWriter super 
// class 	TokenNameCOMMENT_LINE	class 
/** Remove the first character from the string (usually a TAB) and do not print "\n" */	TokenNameCOMMENT_JAVADOC	 Remove the first character from the string (usually a TAB) and do not print "\n" 
public	TokenNamepublic	
void	TokenNamevoid	
println	TokenNameIdentifier	 println
(	TokenNameLPAREN	
String	TokenNameIdentifier	 String
s	TokenNameIdentifier	 s
)	TokenNameRPAREN	
{	TokenNameLBRACE	
// remove '^I' and replace it with 4 spaces 	TokenNameCOMMENT_LINE	remove '^I' and replace it with 4 spaces 
this	TokenNamethis	
.	TokenNameDOT	
qWriter	TokenNameIdentifier	 q Writer
.	TokenNameDOT	
write	TokenNameIdentifier	 write
(	TokenNameLPAREN	
TAB	TokenNameIdentifier	 TAB
+	TokenNamePLUS	
s	TokenNameIdentifier	 s
.	TokenNameDOT	
substring	TokenNameIdentifier	 substring
(	TokenNameLPAREN	
1	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
}	TokenNameRBRACE	
