// This file was generated automatically by the Snowball to Java compiler 	TokenNameCOMMENT_LINE	This file was generated automatically by the Snowball to Java compiler 
package	TokenNamepackage	
org	TokenNameIdentifier	 org
.	TokenNameDOT	
tartarus	TokenNameIdentifier	 tartarus
.	TokenNameDOT	
snowball	TokenNameIdentifier	 snowball
.	TokenNameDOT	
ext	TokenNameIdentifier	 ext
;	TokenNameSEMICOLON	
import	TokenNameimport	
org	TokenNameIdentifier	 org
.	TokenNameDOT	
tartarus	TokenNameIdentifier	 tartarus
.	TokenNameDOT	
snowball	TokenNameIdentifier	 snowball
.	TokenNameDOT	
Among	TokenNameIdentifier	 Among
;	TokenNameSEMICOLON	
import	TokenNameimport	
org	TokenNameIdentifier	 org
.	TokenNameDOT	
tartarus	TokenNameIdentifier	 tartarus
.	TokenNameDOT	
snowball	TokenNameIdentifier	 snowball
.	TokenNameDOT	
SnowballProgram	TokenNameIdentifier	 Snowball Program
;	TokenNameSEMICOLON	
/** * This class was automatically generated by a Snowball to Java compiler * It implements the stemming algorithm defined by a snowball script. */	TokenNameCOMMENT_JAVADOC	 This class was automatically generated by a Snowball to Java compiler It implements the stemming algorithm defined by a snowball script. 
public	TokenNamepublic	
class	TokenNameclass	
IrishStemmer	TokenNameIdentifier	 Irish Stemmer
extends	TokenNameextends	
SnowballProgram	TokenNameIdentifier	 Snowball Program
{	TokenNameLBRACE	
private	TokenNameprivate	
static	TokenNamestatic	
final	TokenNamefinal	
long	TokenNamelong	
serialVersionUID	TokenNameIdentifier	 serial Version UID
=	TokenNameEQUAL	
1L	TokenNameLongLiteral	
;	TokenNameSEMICOLON	
private	TokenNameprivate	
final	TokenNamefinal	
static	TokenNamestatic	
IrishStemmer	TokenNameIdentifier	 Irish Stemmer
methodObject	TokenNameIdentifier	 method Object
=	TokenNameEQUAL	
new	TokenNamenew	
IrishStemmer	TokenNameIdentifier	 Irish Stemmer
(	TokenNameLPAREN	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
private	TokenNameprivate	
final	TokenNamefinal	
static	TokenNamestatic	
Among	TokenNameIdentifier	 Among
a_0	TokenNameIdentifier	 a 0
[	TokenNameLBRACKET	
]	TokenNameRBRACKET	
=	TokenNameEQUAL	
{	TokenNameLBRACE	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"b'"	TokenNameStringLiteral	b'
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
4	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"bh"	TokenNameStringLiteral	bh
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
14	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"bhf"	TokenNameStringLiteral	bhf
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
9	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"bp"	TokenNameStringLiteral	bp
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
11	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"ch"	TokenNameStringLiteral	ch
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
15	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"d'"	TokenNameStringLiteral	d'
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"d'fh"	TokenNameStringLiteral	d'fh
,	TokenNameCOMMA	
5	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
3	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"dh"	TokenNameStringLiteral	dh
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
16	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"dt"	TokenNameStringLiteral	dt
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
13	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"fh"	TokenNameStringLiteral	fh
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
17	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"gc"	TokenNameStringLiteral	gc
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
7	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"gh"	TokenNameStringLiteral	gh
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
18	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"h-"	TokenNameStringLiteral	h-
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"m'"	TokenNameStringLiteral	m'
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
4	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"mb"	TokenNameStringLiteral	mb
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
6	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"mh"	TokenNameStringLiteral	mh
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
19	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"n-"	TokenNameStringLiteral	n-
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"nd"	TokenNameStringLiteral	nd
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
8	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"ng"	TokenNameStringLiteral	ng
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
10	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"ph"	TokenNameStringLiteral	ph
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
20	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"sh"	TokenNameStringLiteral	sh
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
5	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"t-"	TokenNameStringLiteral	t-
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"th"	TokenNameStringLiteral	th
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
21	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"ts"	TokenNameStringLiteral	ts
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
12	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
}	TokenNameRBRACE	
;	TokenNameSEMICOLON	
private	TokenNameprivate	
final	TokenNamefinal	
static	TokenNamestatic	
Among	TokenNameIdentifier	 Among
a_1	TokenNameIdentifier	 a 1
[	TokenNameLBRACKET	
]	TokenNameRBRACKET	
=	TokenNameEQUAL	
{	TokenNameLBRACE	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"’ochta"	TokenNameStringLiteral	’ochta
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"a’ochta"	TokenNameStringLiteral	a’ochta
,	TokenNameCOMMA	
0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"ire"	TokenNameStringLiteral	ire
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"aire"	TokenNameStringLiteral	aire
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"abh"	TokenNameStringLiteral	abh
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"eabh"	TokenNameStringLiteral	eabh
,	TokenNameCOMMA	
4	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"ibh"	TokenNameStringLiteral	ibh
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"aibh"	TokenNameStringLiteral	aibh
,	TokenNameCOMMA	
6	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"amh"	TokenNameStringLiteral	amh
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"eamh"	TokenNameStringLiteral	eamh
,	TokenNameCOMMA	
8	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"imh"	TokenNameStringLiteral	imh
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"aimh"	TokenNameStringLiteral	aimh
,	TokenNameCOMMA	
10	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"’ocht"	TokenNameStringLiteral	’ocht
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"a’ocht"	TokenNameStringLiteral	a’ocht
,	TokenNameCOMMA	
12	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"ir’"	TokenNameStringLiteral	ir’
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"air’"	TokenNameStringLiteral	air’
,	TokenNameCOMMA	
14	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
}	TokenNameRBRACE	
;	TokenNameSEMICOLON	
private	TokenNameprivate	
final	TokenNamefinal	
static	TokenNamestatic	
Among	TokenNameIdentifier	 Among
a_2	TokenNameIdentifier	 a 2
[	TokenNameLBRACKET	
]	TokenNameRBRACKET	
=	TokenNameEQUAL	
{	TokenNameLBRACE	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"—ideacha"	TokenNameStringLiteral	—ideacha
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
6	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"patacha"	TokenNameStringLiteral	patacha
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
5	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"achta"	TokenNameStringLiteral	achta
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"arcachta"	TokenNameStringLiteral	arcachta
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"eachta"	TokenNameStringLiteral	eachta
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"grafa’ochta"	TokenNameStringLiteral	grafa’ochta
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
4	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"paite"	TokenNameStringLiteral	paite
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
5	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"ach"	TokenNameStringLiteral	ach
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"each"	TokenNameStringLiteral	each
,	TokenNameCOMMA	
7	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"—ideach"	TokenNameStringLiteral	—ideach
,	TokenNameCOMMA	
8	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
6	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"gineach"	TokenNameStringLiteral	gineach
,	TokenNameCOMMA	
8	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
3	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"patach"	TokenNameStringLiteral	patach
,	TokenNameCOMMA	
7	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
5	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"grafa’och"	TokenNameStringLiteral	grafa’och
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
4	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"pataigh"	TokenNameStringLiteral	pataigh
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
5	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"—idigh"	TokenNameStringLiteral	—idigh
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
6	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"achtœil"	TokenNameStringLiteral	achtœil
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"eachtœil"	TokenNameStringLiteral	eachtœil
,	TokenNameCOMMA	
15	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"gineas"	TokenNameStringLiteral	gineas
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
3	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"ginis"	TokenNameStringLiteral	ginis
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
3	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"acht"	TokenNameStringLiteral	acht
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"arcacht"	TokenNameStringLiteral	arcacht
,	TokenNameCOMMA	
19	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"eacht"	TokenNameStringLiteral	eacht
,	TokenNameCOMMA	
19	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"grafa’ocht"	TokenNameStringLiteral	grafa’ocht
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
4	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"arcachta’"	TokenNameStringLiteral	arcachta’
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"grafa’ochta’"	TokenNameStringLiteral	grafa’ochta’
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
4	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
}	TokenNameRBRACE	
;	TokenNameSEMICOLON	
private	TokenNameprivate	
final	TokenNamefinal	
static	TokenNamestatic	
Among	TokenNameIdentifier	 Among
a_3	TokenNameIdentifier	 a 3
[	TokenNameLBRACKET	
]	TokenNameRBRACKET	
=	TokenNameEQUAL	
{	TokenNameLBRACE	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"imid"	TokenNameStringLiteral	imid
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"aimid"	TokenNameStringLiteral	aimid
,	TokenNameCOMMA	
0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"’mid"	TokenNameStringLiteral	’mid
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"a’mid"	TokenNameStringLiteral	a’mid
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"adh"	TokenNameStringLiteral	adh
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"eadh"	TokenNameStringLiteral	eadh
,	TokenNameCOMMA	
4	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"faidh"	TokenNameStringLiteral	faidh
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"fidh"	TokenNameStringLiteral	fidh
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"‡il"	TokenNameStringLiteral	‡il
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"ain"	TokenNameStringLiteral	ain
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"tear"	TokenNameStringLiteral	tear
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
,	TokenNameCOMMA	
new	TokenNamenew	
Among	TokenNameIdentifier	 Among
(	TokenNameLPAREN	
"tar"	TokenNameStringLiteral	tar
,	TokenNameCOMMA	
-	TokenNameMINUS	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
""	TokenNameStringLiteral	 
,	TokenNameCOMMA	
methodObject	TokenNameIdentifier	 method Object
)	TokenNameRPAREN	
}	TokenNameRBRACE	
;	TokenNameSEMICOLON	
private	TokenNameprivate	
static	TokenNamestatic	
final	TokenNamefinal	
char	TokenNamechar	
g_v	TokenNameIdentifier	 g v
[	TokenNameLBRACKET	
]	TokenNameRBRACKET	
=	TokenNameEQUAL	
{	TokenNameLBRACE	
17	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
65	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
16	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
0	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
1	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
17	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
4	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
2	TokenNameIntegerLiteral	
}	TokenNameRBRACE	
;	TokenNameSEMICOLON	
private	TokenNameprivate	
int	TokenNameint	
I_p2	TokenNameIdentifier	 I p2
;	TokenNameSEMICOLON	
private	TokenNameprivate	
int	TokenNameint	
I_p1	TokenNameIdentifier	 I p1
;	TokenNameSEMICOLON	
private	TokenNameprivate	
int	TokenNameint	
I_pV	TokenNameIdentifier	 I p V
;	TokenNameSEMICOLON	
private	TokenNameprivate	
void	TokenNamevoid	
copy_from	TokenNameIdentifier	 copy from
(	TokenNameLPAREN	
IrishStemmer	TokenNameIdentifier	 Irish Stemmer
other	TokenNameIdentifier	 other
)	TokenNameRPAREN	
{	TokenNameLBRACE	
I_p2	TokenNameIdentifier	 I p2
=	TokenNameEQUAL	
other	TokenNameIdentifier	 other
.	TokenNameDOT	
I_p2	TokenNameIdentifier	 I p2
;	TokenNameSEMICOLON	
I_p1	TokenNameIdentifier	 I p1
=	TokenNameEQUAL	
other	TokenNameIdentifier	 other
.	TokenNameDOT	
I_p1	TokenNameIdentifier	 I p1
;	TokenNameSEMICOLON	
I_pV	TokenNameIdentifier	 I p V
=	TokenNameEQUAL	
other	TokenNameIdentifier	 other
.	TokenNameDOT	
I_pV	TokenNameIdentifier	 I p V
;	TokenNameSEMICOLON	
super	TokenNamesuper	
.	TokenNameDOT	
copy_from	TokenNameIdentifier	 copy from
(	TokenNameLPAREN	
other	TokenNameIdentifier	 other
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
private	TokenNameprivate	
boolean	TokenNameboolean	
r_mark_regions	TokenNameIdentifier	 r mark regions
(	TokenNameLPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
int	TokenNameint	
v_1	TokenNameIdentifier	 v 1
;	TokenNameSEMICOLON	
int	TokenNameint	
v_3	TokenNameIdentifier	 v 3
;	TokenNameSEMICOLON	
// (, line 28 	TokenNameCOMMENT_LINE	(, line 28 
I_pV	TokenNameIdentifier	 I p V
=	TokenNameEQUAL	
limit	TokenNameIdentifier	 limit
;	TokenNameSEMICOLON	
I_p1	TokenNameIdentifier	 I p1
=	TokenNameEQUAL	
limit	TokenNameIdentifier	 limit
;	TokenNameSEMICOLON	
I_p2	TokenNameIdentifier	 I p2
=	TokenNameEQUAL	
limit	TokenNameIdentifier	 limit
;	TokenNameSEMICOLON	
// do, line 34 	TokenNameCOMMENT_LINE	do, line 34 
v_1	TokenNameIdentifier	 v 1
=	TokenNameEQUAL	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
lab0	TokenNameIdentifier	 lab0
:	TokenNameCOLON	
do	TokenNamedo	
{	TokenNameLBRACE	
// (, line 34 	TokenNameCOMMENT_LINE	(, line 34 
// gopast, line 35 	TokenNameCOMMENT_LINE	gopast, line 35 
golab1	TokenNameIdentifier	 golab1
:	TokenNameCOLON	
while	TokenNamewhile	
(	TokenNameLPAREN	
true	TokenNametrue	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
lab2	TokenNameIdentifier	 lab2
:	TokenNameCOLON	
do	TokenNamedo	
{	TokenNameLBRACE	
if	TokenNameif	
(	TokenNameLPAREN	
!	TokenNameNOT	
(	TokenNameLPAREN	
in_grouping	TokenNameIdentifier	 in grouping
(	TokenNameLPAREN	
g_v	TokenNameIdentifier	 g v
,	TokenNameCOMMA	
97	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
250	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
break	TokenNamebreak	
lab2	TokenNameIdentifier	 lab2
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
break	TokenNamebreak	
golab1	TokenNameIdentifier	 golab1
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
while	TokenNamewhile	
(	TokenNameLPAREN	
false	TokenNamefalse	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
if	TokenNameif	
(	TokenNameLPAREN	
cursor	TokenNameIdentifier	 cursor
>=	TokenNameGREATER_EQUAL	
limit	TokenNameIdentifier	 limit
)	TokenNameRPAREN	
{	TokenNameLBRACE	
break	TokenNamebreak	
lab0	TokenNameIdentifier	 lab0
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
cursor	TokenNameIdentifier	 cursor
++	TokenNamePLUS_PLUS	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
// setmark pV, line 35 	TokenNameCOMMENT_LINE	setmark pV, line 35 
I_pV	TokenNameIdentifier	 I p V
=	TokenNameEQUAL	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
while	TokenNamewhile	
(	TokenNameLPAREN	
false	TokenNamefalse	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
cursor	TokenNameIdentifier	 cursor
=	TokenNameEQUAL	
v_1	TokenNameIdentifier	 v 1
;	TokenNameSEMICOLON	
// do, line 37 	TokenNameCOMMENT_LINE	do, line 37 
v_3	TokenNameIdentifier	 v 3
=	TokenNameEQUAL	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
lab3	TokenNameIdentifier	 lab3
:	TokenNameCOLON	
do	TokenNamedo	
{	TokenNameLBRACE	
// (, line 37 	TokenNameCOMMENT_LINE	(, line 37 
// gopast, line 38 	TokenNameCOMMENT_LINE	gopast, line 38 
golab4	TokenNameIdentifier	 golab4
:	TokenNameCOLON	
while	TokenNamewhile	
(	TokenNameLPAREN	
true	TokenNametrue	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
lab5	TokenNameIdentifier	 lab5
:	TokenNameCOLON	
do	TokenNamedo	
{	TokenNameLBRACE	
if	TokenNameif	
(	TokenNameLPAREN	
!	TokenNameNOT	
(	TokenNameLPAREN	
in_grouping	TokenNameIdentifier	 in grouping
(	TokenNameLPAREN	
g_v	TokenNameIdentifier	 g v
,	TokenNameCOMMA	
97	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
250	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
break	TokenNamebreak	
lab5	TokenNameIdentifier	 lab5
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
break	TokenNamebreak	
golab4	TokenNameIdentifier	 golab4
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
while	TokenNamewhile	
(	TokenNameLPAREN	
false	TokenNamefalse	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
if	TokenNameif	
(	TokenNameLPAREN	
cursor	TokenNameIdentifier	 cursor
>=	TokenNameGREATER_EQUAL	
limit	TokenNameIdentifier	 limit
)	TokenNameRPAREN	
{	TokenNameLBRACE	
break	TokenNamebreak	
lab3	TokenNameIdentifier	 lab3
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
cursor	TokenNameIdentifier	 cursor
++	TokenNamePLUS_PLUS	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
// gopast, line 38 	TokenNameCOMMENT_LINE	gopast, line 38 
golab6	TokenNameIdentifier	 golab6
:	TokenNameCOLON	
while	TokenNamewhile	
(	TokenNameLPAREN	
true	TokenNametrue	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
lab7	TokenNameIdentifier	 lab7
:	TokenNameCOLON	
do	TokenNamedo	
{	TokenNameLBRACE	
if	TokenNameif	
(	TokenNameLPAREN	
!	TokenNameNOT	
(	TokenNameLPAREN	
out_grouping	TokenNameIdentifier	 out grouping
(	TokenNameLPAREN	
g_v	TokenNameIdentifier	 g v
,	TokenNameCOMMA	
97	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
250	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
break	TokenNamebreak	
lab7	TokenNameIdentifier	 lab7
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
break	TokenNamebreak	
golab6	TokenNameIdentifier	 golab6
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
while	TokenNamewhile	
(	TokenNameLPAREN	
false	TokenNamefalse	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
if	TokenNameif	
(	TokenNameLPAREN	
cursor	TokenNameIdentifier	 cursor
>=	TokenNameGREATER_EQUAL	
limit	TokenNameIdentifier	 limit
)	TokenNameRPAREN	
{	TokenNameLBRACE	
break	TokenNamebreak	
lab3	TokenNameIdentifier	 lab3
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
cursor	TokenNameIdentifier	 cursor
++	TokenNamePLUS_PLUS	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
// setmark p1, line 38 	TokenNameCOMMENT_LINE	setmark p1, line 38 
I_p1	TokenNameIdentifier	 I p1
=	TokenNameEQUAL	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
// gopast, line 39 	TokenNameCOMMENT_LINE	gopast, line 39 
golab8	TokenNameIdentifier	 golab8
:	TokenNameCOLON	
while	TokenNamewhile	
(	TokenNameLPAREN	
true	TokenNametrue	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
lab9	TokenNameIdentifier	 lab9
:	TokenNameCOLON	
do	TokenNamedo	
{	TokenNameLBRACE	
if	TokenNameif	
(	TokenNameLPAREN	
!	TokenNameNOT	
(	TokenNameLPAREN	
in_grouping	TokenNameIdentifier	 in grouping
(	TokenNameLPAREN	
g_v	TokenNameIdentifier	 g v
,	TokenNameCOMMA	
97	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
250	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
break	TokenNamebreak	
lab9	TokenNameIdentifier	 lab9
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
break	TokenNamebreak	
golab8	TokenNameIdentifier	 golab8
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
while	TokenNamewhile	
(	TokenNameLPAREN	
false	TokenNamefalse	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
if	TokenNameif	
(	TokenNameLPAREN	
cursor	TokenNameIdentifier	 cursor
>=	TokenNameGREATER_EQUAL	
limit	TokenNameIdentifier	 limit
)	TokenNameRPAREN	
{	TokenNameLBRACE	
break	TokenNamebreak	
lab3	TokenNameIdentifier	 lab3
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
cursor	TokenNameIdentifier	 cursor
++	TokenNamePLUS_PLUS	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
// gopast, line 39 	TokenNameCOMMENT_LINE	gopast, line 39 
golab10	TokenNameIdentifier	 golab10
:	TokenNameCOLON	
while	TokenNamewhile	
(	TokenNameLPAREN	
true	TokenNametrue	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
lab11	TokenNameIdentifier	 lab11
:	TokenNameCOLON	
do	TokenNamedo	
{	TokenNameLBRACE	
if	TokenNameif	
(	TokenNameLPAREN	
!	TokenNameNOT	
(	TokenNameLPAREN	
out_grouping	TokenNameIdentifier	 out grouping
(	TokenNameLPAREN	
g_v	TokenNameIdentifier	 g v
,	TokenNameCOMMA	
97	TokenNameIntegerLiteral	
,	TokenNameCOMMA	
250	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
break	TokenNamebreak	
lab11	TokenNameIdentifier	 lab11
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
break	TokenNamebreak	
golab10	TokenNameIdentifier	 golab10
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
while	TokenNamewhile	
(	TokenNameLPAREN	
false	TokenNamefalse	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
if	TokenNameif	
(	TokenNameLPAREN	
cursor	TokenNameIdentifier	 cursor
>=	TokenNameGREATER_EQUAL	
limit	TokenNameIdentifier	 limit
)	TokenNameRPAREN	
{	TokenNameLBRACE	
break	TokenNamebreak	
lab3	TokenNameIdentifier	 lab3
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
cursor	TokenNameIdentifier	 cursor
++	TokenNamePLUS_PLUS	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
// setmark p2, line 39 	TokenNameCOMMENT_LINE	setmark p2, line 39 
I_p2	TokenNameIdentifier	 I p2
=	TokenNameEQUAL	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
while	TokenNamewhile	
(	TokenNameLPAREN	
false	TokenNamefalse	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
cursor	TokenNameIdentifier	 cursor
=	TokenNameEQUAL	
v_3	TokenNameIdentifier	 v 3
;	TokenNameSEMICOLON	
return	TokenNamereturn	
true	TokenNametrue	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
private	TokenNameprivate	
boolean	TokenNameboolean	
r_initial_morph	TokenNameIdentifier	 r initial morph
(	TokenNameLPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
int	TokenNameint	
among_var	TokenNameIdentifier	 among var
;	TokenNameSEMICOLON	
// (, line 43 	TokenNameCOMMENT_LINE	(, line 43 
// [, line 44 	TokenNameCOMMENT_LINE	[, line 44 
bra	TokenNameIdentifier	 bra
=	TokenNameEQUAL	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
// substring, line 44 	TokenNameCOMMENT_LINE	substring, line 44 
among_var	TokenNameIdentifier	 among var
=	TokenNameEQUAL	
find_among	TokenNameIdentifier	 find among
(	TokenNameLPAREN	
a_0	TokenNameIdentifier	 a 0
,	TokenNameCOMMA	
24	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
if	TokenNameif	
(	TokenNameLPAREN	
among_var	TokenNameIdentifier	 among var
==	TokenNameEQUAL_EQUAL	
0	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
return	TokenNamereturn	
false	TokenNamefalse	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
// ], line 44 	TokenNameCOMMENT_LINE	], line 44 
ket	TokenNameIdentifier	 ket
=	TokenNameEQUAL	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
switch	TokenNameswitch	
(	TokenNameLPAREN	
among_var	TokenNameIdentifier	 among var
)	TokenNameRPAREN	
{	TokenNameLBRACE	
case	TokenNamecase	
0	TokenNameIntegerLiteral	
:	TokenNameCOLON	
return	TokenNamereturn	
false	TokenNamefalse	
;	TokenNameSEMICOLON	
case	TokenNamecase	
1	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 46 	TokenNameCOMMENT_LINE	(, line 46 
// delete, line 46 	TokenNameCOMMENT_LINE	delete, line 46 
slice_del	TokenNameIdentifier	 slice del
(	TokenNameLPAREN	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
2	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 50 	TokenNameCOMMENT_LINE	(, line 50 
// delete, line 50 	TokenNameCOMMENT_LINE	delete, line 50 
slice_del	TokenNameIdentifier	 slice del
(	TokenNameLPAREN	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
3	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 52 	TokenNameCOMMENT_LINE	(, line 52 
// <-, line 52 	TokenNameCOMMENT_LINE	<-, line 52 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"f"	TokenNameStringLiteral	f
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
4	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 55 	TokenNameCOMMENT_LINE	(, line 55 
// delete, line 55 	TokenNameCOMMENT_LINE	delete, line 55 
slice_del	TokenNameIdentifier	 slice del
(	TokenNameLPAREN	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
5	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 58 	TokenNameCOMMENT_LINE	(, line 58 
// <-, line 58 	TokenNameCOMMENT_LINE	<-, line 58 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"s"	TokenNameStringLiteral	s
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
6	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 61 	TokenNameCOMMENT_LINE	(, line 61 
// <-, line 61 	TokenNameCOMMENT_LINE	<-, line 61 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"b"	TokenNameStringLiteral	b
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
7	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 63 	TokenNameCOMMENT_LINE	(, line 63 
// <-, line 63 	TokenNameCOMMENT_LINE	<-, line 63 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"c"	TokenNameStringLiteral	c
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
8	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 65 	TokenNameCOMMENT_LINE	(, line 65 
// <-, line 65 	TokenNameCOMMENT_LINE	<-, line 65 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"d"	TokenNameStringLiteral	d
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
9	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 67 	TokenNameCOMMENT_LINE	(, line 67 
// <-, line 67 	TokenNameCOMMENT_LINE	<-, line 67 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"f"	TokenNameStringLiteral	f
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
10	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 69 	TokenNameCOMMENT_LINE	(, line 69 
// <-, line 69 	TokenNameCOMMENT_LINE	<-, line 69 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"g"	TokenNameStringLiteral	g
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
11	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 71 	TokenNameCOMMENT_LINE	(, line 71 
// <-, line 71 	TokenNameCOMMENT_LINE	<-, line 71 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"p"	TokenNameStringLiteral	p
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
12	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 73 	TokenNameCOMMENT_LINE	(, line 73 
// <-, line 73 	TokenNameCOMMENT_LINE	<-, line 73 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"s"	TokenNameStringLiteral	s
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
13	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 75 	TokenNameCOMMENT_LINE	(, line 75 
// <-, line 75 	TokenNameCOMMENT_LINE	<-, line 75 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"t"	TokenNameStringLiteral	t
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
14	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 79 	TokenNameCOMMENT_LINE	(, line 79 
// <-, line 79 	TokenNameCOMMENT_LINE	<-, line 79 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"b"	TokenNameStringLiteral	b
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
15	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 81 	TokenNameCOMMENT_LINE	(, line 81 
// <-, line 81 	TokenNameCOMMENT_LINE	<-, line 81 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"c"	TokenNameStringLiteral	c
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
16	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 83 	TokenNameCOMMENT_LINE	(, line 83 
// <-, line 83 	TokenNameCOMMENT_LINE	<-, line 83 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"d"	TokenNameStringLiteral	d
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
17	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 85 	TokenNameCOMMENT_LINE	(, line 85 
// <-, line 85 	TokenNameCOMMENT_LINE	<-, line 85 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"f"	TokenNameStringLiteral	f
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
18	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 87 	TokenNameCOMMENT_LINE	(, line 87 
// <-, line 87 	TokenNameCOMMENT_LINE	<-, line 87 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"g"	TokenNameStringLiteral	g
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
19	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 89 	TokenNameCOMMENT_LINE	(, line 89 
// <-, line 89 	TokenNameCOMMENT_LINE	<-, line 89 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"m"	TokenNameStringLiteral	m
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
20	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 91 	TokenNameCOMMENT_LINE	(, line 91 
// <-, line 91 	TokenNameCOMMENT_LINE	<-, line 91 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"p"	TokenNameStringLiteral	p
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
21	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 93 	TokenNameCOMMENT_LINE	(, line 93 
// <-, line 93 	TokenNameCOMMENT_LINE	<-, line 93 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"t"	TokenNameStringLiteral	t
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
return	TokenNamereturn	
true	TokenNametrue	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
private	TokenNameprivate	
boolean	TokenNameboolean	
r_RV	TokenNameIdentifier	 r  RV
(	TokenNameLPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
if	TokenNameif	
(	TokenNameLPAREN	
!	TokenNameNOT	
(	TokenNameLPAREN	
I_pV	TokenNameIdentifier	 I p V
<=	TokenNameLESS_EQUAL	
cursor	TokenNameIdentifier	 cursor
)	TokenNameRPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
return	TokenNamereturn	
false	TokenNamefalse	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
return	TokenNamereturn	
true	TokenNametrue	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
private	TokenNameprivate	
boolean	TokenNameboolean	
r_R1	TokenNameIdentifier	 r  R1
(	TokenNameLPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
if	TokenNameif	
(	TokenNameLPAREN	
!	TokenNameNOT	
(	TokenNameLPAREN	
I_p1	TokenNameIdentifier	 I p1
<=	TokenNameLESS_EQUAL	
cursor	TokenNameIdentifier	 cursor
)	TokenNameRPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
return	TokenNamereturn	
false	TokenNamefalse	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
return	TokenNamereturn	
true	TokenNametrue	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
private	TokenNameprivate	
boolean	TokenNameboolean	
r_R2	TokenNameIdentifier	 r  R2
(	TokenNameLPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
if	TokenNameif	
(	TokenNameLPAREN	
!	TokenNameNOT	
(	TokenNameLPAREN	
I_p2	TokenNameIdentifier	 I p2
<=	TokenNameLESS_EQUAL	
cursor	TokenNameIdentifier	 cursor
)	TokenNameRPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
return	TokenNamereturn	
false	TokenNamefalse	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
return	TokenNamereturn	
true	TokenNametrue	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
private	TokenNameprivate	
boolean	TokenNameboolean	
r_noun_sfx	TokenNameIdentifier	 r noun sfx
(	TokenNameLPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
int	TokenNameint	
among_var	TokenNameIdentifier	 among var
;	TokenNameSEMICOLON	
// (, line 103 	TokenNameCOMMENT_LINE	(, line 103 
// [, line 104 	TokenNameCOMMENT_LINE	[, line 104 
ket	TokenNameIdentifier	 ket
=	TokenNameEQUAL	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
// substring, line 104 	TokenNameCOMMENT_LINE	substring, line 104 
among_var	TokenNameIdentifier	 among var
=	TokenNameEQUAL	
find_among_b	TokenNameIdentifier	 find among b
(	TokenNameLPAREN	
a_1	TokenNameIdentifier	 a 1
,	TokenNameCOMMA	
16	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
if	TokenNameif	
(	TokenNameLPAREN	
among_var	TokenNameIdentifier	 among var
==	TokenNameEQUAL_EQUAL	
0	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
return	TokenNamereturn	
false	TokenNamefalse	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
// ], line 104 	TokenNameCOMMENT_LINE	], line 104 
bra	TokenNameIdentifier	 bra
=	TokenNameEQUAL	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
switch	TokenNameswitch	
(	TokenNameLPAREN	
among_var	TokenNameIdentifier	 among var
)	TokenNameRPAREN	
{	TokenNameLBRACE	
case	TokenNamecase	
0	TokenNameIntegerLiteral	
:	TokenNameCOLON	
return	TokenNamereturn	
false	TokenNamefalse	
;	TokenNameSEMICOLON	
case	TokenNamecase	
1	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 108 	TokenNameCOMMENT_LINE	(, line 108 
// call R1, line 108 	TokenNameCOMMENT_LINE	call R1, line 108 
if	TokenNameif	
(	TokenNameLPAREN	
!	TokenNameNOT	
r_R1	TokenNameIdentifier	 r  R1
(	TokenNameLPAREN	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
return	TokenNamereturn	
false	TokenNamefalse	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
// delete, line 108 	TokenNameCOMMENT_LINE	delete, line 108 
slice_del	TokenNameIdentifier	 slice del
(	TokenNameLPAREN	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
2	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 110 	TokenNameCOMMENT_LINE	(, line 110 
// call R2, line 110 	TokenNameCOMMENT_LINE	call R2, line 110 
if	TokenNameif	
(	TokenNameLPAREN	
!	TokenNameNOT	
r_R2	TokenNameIdentifier	 r  R2
(	TokenNameLPAREN	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
return	TokenNamereturn	
false	TokenNamefalse	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
// delete, line 110 	TokenNameCOMMENT_LINE	delete, line 110 
slice_del	TokenNameIdentifier	 slice del
(	TokenNameLPAREN	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
return	TokenNamereturn	
true	TokenNametrue	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
private	TokenNameprivate	
boolean	TokenNameboolean	
r_deriv	TokenNameIdentifier	 r deriv
(	TokenNameLPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
int	TokenNameint	
among_var	TokenNameIdentifier	 among var
;	TokenNameSEMICOLON	
// (, line 113 	TokenNameCOMMENT_LINE	(, line 113 
// [, line 114 	TokenNameCOMMENT_LINE	[, line 114 
ket	TokenNameIdentifier	 ket
=	TokenNameEQUAL	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
// substring, line 114 	TokenNameCOMMENT_LINE	substring, line 114 
among_var	TokenNameIdentifier	 among var
=	TokenNameEQUAL	
find_among_b	TokenNameIdentifier	 find among b
(	TokenNameLPAREN	
a_2	TokenNameIdentifier	 a 2
,	TokenNameCOMMA	
25	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
if	TokenNameif	
(	TokenNameLPAREN	
among_var	TokenNameIdentifier	 among var
==	TokenNameEQUAL_EQUAL	
0	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
return	TokenNamereturn	
false	TokenNamefalse	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
// ], line 114 	TokenNameCOMMENT_LINE	], line 114 
bra	TokenNameIdentifier	 bra
=	TokenNameEQUAL	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
switch	TokenNameswitch	
(	TokenNameLPAREN	
among_var	TokenNameIdentifier	 among var
)	TokenNameRPAREN	
{	TokenNameLBRACE	
case	TokenNamecase	
0	TokenNameIntegerLiteral	
:	TokenNameCOLON	
return	TokenNamereturn	
false	TokenNamefalse	
;	TokenNameSEMICOLON	
case	TokenNamecase	
1	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 116 	TokenNameCOMMENT_LINE	(, line 116 
// call R2, line 116 	TokenNameCOMMENT_LINE	call R2, line 116 
if	TokenNameif	
(	TokenNameLPAREN	
!	TokenNameNOT	
r_R2	TokenNameIdentifier	 r  R2
(	TokenNameLPAREN	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
return	TokenNamereturn	
false	TokenNamefalse	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
// delete, line 116 	TokenNameCOMMENT_LINE	delete, line 116 
slice_del	TokenNameIdentifier	 slice del
(	TokenNameLPAREN	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
2	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 118 	TokenNameCOMMENT_LINE	(, line 118 
// <-, line 118 	TokenNameCOMMENT_LINE	<-, line 118 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"arc"	TokenNameStringLiteral	arc
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
3	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 120 	TokenNameCOMMENT_LINE	(, line 120 
// <-, line 120 	TokenNameCOMMENT_LINE	<-, line 120 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"gin"	TokenNameStringLiteral	gin
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
4	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 122 	TokenNameCOMMENT_LINE	(, line 122 
// <-, line 122 	TokenNameCOMMENT_LINE	<-, line 122 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"graf"	TokenNameStringLiteral	graf
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
5	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 124 	TokenNameCOMMENT_LINE	(, line 124 
// <-, line 124 	TokenNameCOMMENT_LINE	<-, line 124 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"paite"	TokenNameStringLiteral	paite
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
6	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 126 	TokenNameCOMMENT_LINE	(, line 126 
// <-, line 126 	TokenNameCOMMENT_LINE	<-, line 126 
slice_from	TokenNameIdentifier	 slice from
(	TokenNameLPAREN	
"—id"	TokenNameStringLiteral	—id
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
return	TokenNamereturn	
true	TokenNametrue	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
private	TokenNameprivate	
boolean	TokenNameboolean	
r_verb_sfx	TokenNameIdentifier	 r verb sfx
(	TokenNameLPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
int	TokenNameint	
among_var	TokenNameIdentifier	 among var
;	TokenNameSEMICOLON	
// (, line 129 	TokenNameCOMMENT_LINE	(, line 129 
// [, line 130 	TokenNameCOMMENT_LINE	[, line 130 
ket	TokenNameIdentifier	 ket
=	TokenNameEQUAL	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
// substring, line 130 	TokenNameCOMMENT_LINE	substring, line 130 
among_var	TokenNameIdentifier	 among var
=	TokenNameEQUAL	
find_among_b	TokenNameIdentifier	 find among b
(	TokenNameLPAREN	
a_3	TokenNameIdentifier	 a 3
,	TokenNameCOMMA	
12	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
if	TokenNameif	
(	TokenNameLPAREN	
among_var	TokenNameIdentifier	 among var
==	TokenNameEQUAL_EQUAL	
0	TokenNameIntegerLiteral	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
return	TokenNamereturn	
false	TokenNamefalse	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
// ], line 130 	TokenNameCOMMENT_LINE	], line 130 
bra	TokenNameIdentifier	 bra
=	TokenNameEQUAL	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
switch	TokenNameswitch	
(	TokenNameLPAREN	
among_var	TokenNameIdentifier	 among var
)	TokenNameRPAREN	
{	TokenNameLBRACE	
case	TokenNamecase	
0	TokenNameIntegerLiteral	
:	TokenNameCOLON	
return	TokenNamereturn	
false	TokenNamefalse	
;	TokenNameSEMICOLON	
case	TokenNamecase	
1	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 133 	TokenNameCOMMENT_LINE	(, line 133 
// call RV, line 133 	TokenNameCOMMENT_LINE	call RV, line 133 
if	TokenNameif	
(	TokenNameLPAREN	
!	TokenNameNOT	
r_RV	TokenNameIdentifier	 r  RV
(	TokenNameLPAREN	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
return	TokenNamereturn	
false	TokenNamefalse	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
// delete, line 133 	TokenNameCOMMENT_LINE	delete, line 133 
slice_del	TokenNameIdentifier	 slice del
(	TokenNameLPAREN	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
case	TokenNamecase	
2	TokenNameIntegerLiteral	
:	TokenNameCOLON	
// (, line 138 	TokenNameCOMMENT_LINE	(, line 138 
// call R1, line 138 	TokenNameCOMMENT_LINE	call R1, line 138 
if	TokenNameif	
(	TokenNameLPAREN	
!	TokenNameNOT	
r_R1	TokenNameIdentifier	 r  R1
(	TokenNameLPAREN	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
return	TokenNamereturn	
false	TokenNamefalse	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
// delete, line 138 	TokenNameCOMMENT_LINE	delete, line 138 
slice_del	TokenNameIdentifier	 slice del
(	TokenNameLPAREN	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
break	TokenNamebreak	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
return	TokenNamereturn	
true	TokenNametrue	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
public	TokenNamepublic	
boolean	TokenNameboolean	
stem	TokenNameIdentifier	 stem
(	TokenNameLPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
int	TokenNameint	
v_1	TokenNameIdentifier	 v 1
;	TokenNameSEMICOLON	
int	TokenNameint	
v_2	TokenNameIdentifier	 v 2
;	TokenNameSEMICOLON	
int	TokenNameint	
v_3	TokenNameIdentifier	 v 3
;	TokenNameSEMICOLON	
int	TokenNameint	
v_4	TokenNameIdentifier	 v 4
;	TokenNameSEMICOLON	
int	TokenNameint	
v_5	TokenNameIdentifier	 v 5
;	TokenNameSEMICOLON	
// (, line 143 	TokenNameCOMMENT_LINE	(, line 143 
// do, line 144 	TokenNameCOMMENT_LINE	do, line 144 
v_1	TokenNameIdentifier	 v 1
=	TokenNameEQUAL	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
lab0	TokenNameIdentifier	 lab0
:	TokenNameCOLON	
do	TokenNamedo	
{	TokenNameLBRACE	
// call initial_morph, line 144 	TokenNameCOMMENT_LINE	call initial_morph, line 144 
if	TokenNameif	
(	TokenNameLPAREN	
!	TokenNameNOT	
r_initial_morph	TokenNameIdentifier	 r initial morph
(	TokenNameLPAREN	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
break	TokenNamebreak	
lab0	TokenNameIdentifier	 lab0
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
}	TokenNameRBRACE	
while	TokenNamewhile	
(	TokenNameLPAREN	
false	TokenNamefalse	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
cursor	TokenNameIdentifier	 cursor
=	TokenNameEQUAL	
v_1	TokenNameIdentifier	 v 1
;	TokenNameSEMICOLON	
// do, line 145 	TokenNameCOMMENT_LINE	do, line 145 
v_2	TokenNameIdentifier	 v 2
=	TokenNameEQUAL	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
lab1	TokenNameIdentifier	 lab1
:	TokenNameCOLON	
do	TokenNamedo	
{	TokenNameLBRACE	
// call mark_regions, line 145 	TokenNameCOMMENT_LINE	call mark_regions, line 145 
if	TokenNameif	
(	TokenNameLPAREN	
!	TokenNameNOT	
r_mark_regions	TokenNameIdentifier	 r mark regions
(	TokenNameLPAREN	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
break	TokenNamebreak	
lab1	TokenNameIdentifier	 lab1
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
}	TokenNameRBRACE	
while	TokenNamewhile	
(	TokenNameLPAREN	
false	TokenNamefalse	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
cursor	TokenNameIdentifier	 cursor
=	TokenNameEQUAL	
v_2	TokenNameIdentifier	 v 2
;	TokenNameSEMICOLON	
// backwards, line 146 	TokenNameCOMMENT_LINE	backwards, line 146 
limit_backward	TokenNameIdentifier	 limit backward
=	TokenNameEQUAL	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
cursor	TokenNameIdentifier	 cursor
=	TokenNameEQUAL	
limit	TokenNameIdentifier	 limit
;	TokenNameSEMICOLON	
// (, line 146 	TokenNameCOMMENT_LINE	(, line 146 
// do, line 147 	TokenNameCOMMENT_LINE	do, line 147 
v_3	TokenNameIdentifier	 v 3
=	TokenNameEQUAL	
limit	TokenNameIdentifier	 limit
-	TokenNameMINUS	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
lab2	TokenNameIdentifier	 lab2
:	TokenNameCOLON	
do	TokenNamedo	
{	TokenNameLBRACE	
// call noun_sfx, line 147 	TokenNameCOMMENT_LINE	call noun_sfx, line 147 
if	TokenNameif	
(	TokenNameLPAREN	
!	TokenNameNOT	
r_noun_sfx	TokenNameIdentifier	 r noun sfx
(	TokenNameLPAREN	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
break	TokenNamebreak	
lab2	TokenNameIdentifier	 lab2
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
}	TokenNameRBRACE	
while	TokenNamewhile	
(	TokenNameLPAREN	
false	TokenNamefalse	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
cursor	TokenNameIdentifier	 cursor
=	TokenNameEQUAL	
limit	TokenNameIdentifier	 limit
-	TokenNameMINUS	
v_3	TokenNameIdentifier	 v 3
;	TokenNameSEMICOLON	
// do, line 148 	TokenNameCOMMENT_LINE	do, line 148 
v_4	TokenNameIdentifier	 v 4
=	TokenNameEQUAL	
limit	TokenNameIdentifier	 limit
-	TokenNameMINUS	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
lab3	TokenNameIdentifier	 lab3
:	TokenNameCOLON	
do	TokenNamedo	
{	TokenNameLBRACE	
// call deriv, line 148 	TokenNameCOMMENT_LINE	call deriv, line 148 
if	TokenNameif	
(	TokenNameLPAREN	
!	TokenNameNOT	
r_deriv	TokenNameIdentifier	 r deriv
(	TokenNameLPAREN	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
break	TokenNamebreak	
lab3	TokenNameIdentifier	 lab3
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
}	TokenNameRBRACE	
while	TokenNamewhile	
(	TokenNameLPAREN	
false	TokenNamefalse	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
cursor	TokenNameIdentifier	 cursor
=	TokenNameEQUAL	
limit	TokenNameIdentifier	 limit
-	TokenNameMINUS	
v_4	TokenNameIdentifier	 v 4
;	TokenNameSEMICOLON	
// do, line 149 	TokenNameCOMMENT_LINE	do, line 149 
v_5	TokenNameIdentifier	 v 5
=	TokenNameEQUAL	
limit	TokenNameIdentifier	 limit
-	TokenNameMINUS	
cursor	TokenNameIdentifier	 cursor
;	TokenNameSEMICOLON	
lab4	TokenNameIdentifier	 lab4
:	TokenNameCOLON	
do	TokenNamedo	
{	TokenNameLBRACE	
// call verb_sfx, line 149 	TokenNameCOMMENT_LINE	call verb_sfx, line 149 
if	TokenNameif	
(	TokenNameLPAREN	
!	TokenNameNOT	
r_verb_sfx	TokenNameIdentifier	 r verb sfx
(	TokenNameLPAREN	
)	TokenNameRPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
break	TokenNamebreak	
lab4	TokenNameIdentifier	 lab4
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
}	TokenNameRBRACE	
while	TokenNamewhile	
(	TokenNameLPAREN	
false	TokenNamefalse	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
cursor	TokenNameIdentifier	 cursor
=	TokenNameEQUAL	
limit	TokenNameIdentifier	 limit
-	TokenNameMINUS	
v_5	TokenNameIdentifier	 v 5
;	TokenNameSEMICOLON	
cursor	TokenNameIdentifier	 cursor
=	TokenNameEQUAL	
limit_backward	TokenNameIdentifier	 limit backward
;	TokenNameSEMICOLON	
return	TokenNamereturn	
true	TokenNametrue	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
public	TokenNamepublic	
boolean	TokenNameboolean	
equals	TokenNameIdentifier	 equals
(	TokenNameLPAREN	
Object	TokenNameIdentifier	 Object
o	TokenNameIdentifier	 o
)	TokenNameRPAREN	
{	TokenNameLBRACE	
return	TokenNamereturn	
o	TokenNameIdentifier	 o
instanceof	TokenNameinstanceof	
IrishStemmer	TokenNameIdentifier	 Irish Stemmer
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
public	TokenNamepublic	
int	TokenNameint	
hashCode	TokenNameIdentifier	 hash Code
(	TokenNameLPAREN	
)	TokenNameRPAREN	
{	TokenNameLBRACE	
return	TokenNamereturn	
IrishStemmer	TokenNameIdentifier	 Irish Stemmer
.	TokenNameDOT	
class	TokenNameclass	
.	TokenNameDOT	
getName	TokenNameIdentifier	 get Name
(	TokenNameLPAREN	
)	TokenNameRPAREN	
.	TokenNameDOT	
hashCode	TokenNameIdentifier	 hash Code
(	TokenNameLPAREN	
)	TokenNameRPAREN	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
}	TokenNameRBRACE	
