/* Generated By:JavaCC: Do not edit this line. QueryParserConstants.java */	TokenNameCOMMENT_BLOCK	 Generated By:JavaCC: Do not edit this line. QueryParserConstants.java 
package	TokenNamepackage	
org	TokenNameIdentifier	 org
.	TokenNameDOT	
apache	TokenNameIdentifier	 apache
.	TokenNameDOT	
lucene	TokenNameIdentifier	 lucene
.	TokenNameDOT	
queryParser	TokenNameIdentifier	 query Parser
.	TokenNameDOT	
surround	TokenNameIdentifier	 surround
.	TokenNameDOT	
parser	TokenNameIdentifier	 parser
;	TokenNameSEMICOLON	
/** * Token literal values and constants. * Generated by org.javacc.parser.OtherFilesGen#start() */	TokenNameCOMMENT_JAVADOC	 Token literal values and constants. Generated by org.javacc.parser.OtherFilesGen#start() 
public	TokenNamepublic	
interface	TokenNameinterface	
QueryParserConstants	TokenNameIdentifier	 Query Parser Constants
{	TokenNameLBRACE	
/** End of File. */	TokenNameCOMMENT_JAVADOC	 End of File. 
int	TokenNameint	
EOF	TokenNameIdentifier	 EOF
=	TokenNameEQUAL	
0	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
_NUM_CHAR	TokenNameIdentifier	 NUM  CHAR
=	TokenNameEQUAL	
1	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
_TERM_CHAR	TokenNameIdentifier	 TERM  CHAR
=	TokenNameEQUAL	
2	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
_WHITESPACE	TokenNameIdentifier	 WHITESPACE
=	TokenNameEQUAL	
3	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
_STAR	TokenNameIdentifier	 STAR
=	TokenNameEQUAL	
4	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
_ONE_CHAR	TokenNameIdentifier	 ONE  CHAR
=	TokenNameEQUAL	
5	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
_DISTOP_NUM	TokenNameIdentifier	 DISTOP  NUM
=	TokenNameEQUAL	
6	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
OR	TokenNameIdentifier	 OR
=	TokenNameEQUAL	
8	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
AND	TokenNameIdentifier	 AND
=	TokenNameEQUAL	
9	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
NOT	TokenNameIdentifier	 NOT
=	TokenNameEQUAL	
10	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
W	TokenNameIdentifier	 W
=	TokenNameEQUAL	
11	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
N	TokenNameIdentifier	 N
=	TokenNameEQUAL	
12	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
LPAREN	TokenNameIdentifier	 LPAREN
=	TokenNameEQUAL	
13	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
RPAREN	TokenNameIdentifier	 RPAREN
=	TokenNameEQUAL	
14	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
COMMA	TokenNameIdentifier	 COMMA
=	TokenNameEQUAL	
15	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
COLON	TokenNameIdentifier	 COLON
=	TokenNameEQUAL	
16	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
CARAT	TokenNameIdentifier	 CARAT
=	TokenNameEQUAL	
17	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
TRUNCQUOTED	TokenNameIdentifier	 TRUNCQUOTED
=	TokenNameEQUAL	
18	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
QUOTED	TokenNameIdentifier	 QUOTED
=	TokenNameEQUAL	
19	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
SUFFIXTERM	TokenNameIdentifier	 SUFFIXTERM
=	TokenNameEQUAL	
20	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
TRUNCTERM	TokenNameIdentifier	 TRUNCTERM
=	TokenNameEQUAL	
21	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
TERM	TokenNameIdentifier	 TERM
=	TokenNameEQUAL	
22	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** RegularExpression Id. */	TokenNameCOMMENT_JAVADOC	 RegularExpression Id. 
int	TokenNameint	
NUMBER	TokenNameIdentifier	 NUMBER
=	TokenNameEQUAL	
23	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** Lexical state. */	TokenNameCOMMENT_JAVADOC	 Lexical state. 
int	TokenNameint	
Boost	TokenNameIdentifier	 Boost
=	TokenNameEQUAL	
0	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** Lexical state. */	TokenNameCOMMENT_JAVADOC	 Lexical state. 
int	TokenNameint	
DEFAULT	TokenNameIdentifier	 DEFAULT
=	TokenNameEQUAL	
1	TokenNameIntegerLiteral	
;	TokenNameSEMICOLON	
/** Literal token values. */	TokenNameCOMMENT_JAVADOC	 Literal token values. 
String	TokenNameIdentifier	 String
[	TokenNameLBRACKET	
]	TokenNameRBRACKET	
tokenImage	TokenNameIdentifier	 token Image
=	TokenNameEQUAL	
{	TokenNameLBRACE	
"<EOF>"	TokenNameStringLiteral	<EOF>
,	TokenNameCOMMA	
"<_NUM_CHAR>"	TokenNameStringLiteral	<_NUM_CHAR>
,	TokenNameCOMMA	
"<_TERM_CHAR>"	TokenNameStringLiteral	<_TERM_CHAR>
,	TokenNameCOMMA	
"<_WHITESPACE>"	TokenNameStringLiteral	<_WHITESPACE>
,	TokenNameCOMMA	
""*""	TokenNameStringLiteral	"*"
,	TokenNameCOMMA	
""?""	TokenNameStringLiteral	"?"
,	TokenNameCOMMA	
"<_DISTOP_NUM>"	TokenNameStringLiteral	<_DISTOP_NUM>
,	TokenNameCOMMA	
"<token of kind 7>"	TokenNameStringLiteral	<token of kind 7>
,	TokenNameCOMMA	
"<OR>"	TokenNameStringLiteral	<OR>
,	TokenNameCOMMA	
"<AND>"	TokenNameStringLiteral	<AND>
,	TokenNameCOMMA	
"<NOT>"	TokenNameStringLiteral	<NOT>
,	TokenNameCOMMA	
"<W>"	TokenNameStringLiteral	<W>
,	TokenNameCOMMA	
"<N>"	TokenNameStringLiteral	<N>
,	TokenNameCOMMA	
""(""	TokenNameStringLiteral	"("
,	TokenNameCOMMA	
"")""	TokenNameStringLiteral	")"
,	TokenNameCOMMA	
"",""	TokenNameStringLiteral	","
,	TokenNameCOMMA	
"":""	TokenNameStringLiteral	":"
,	TokenNameCOMMA	
""^""	TokenNameStringLiteral	"^"
,	TokenNameCOMMA	
"<TRUNCQUOTED>"	TokenNameStringLiteral	<TRUNCQUOTED>
,	TokenNameCOMMA	
"<QUOTED>"	TokenNameStringLiteral	<QUOTED>
,	TokenNameCOMMA	
"<SUFFIXTERM>"	TokenNameStringLiteral	<SUFFIXTERM>
,	TokenNameCOMMA	
"<TRUNCTERM>"	TokenNameStringLiteral	<TRUNCTERM>
,	TokenNameCOMMA	
"<TERM>"	TokenNameStringLiteral	<TERM>
,	TokenNameCOMMA	
"<NUMBER>"	TokenNameStringLiteral	<NUMBER>
,	TokenNameCOMMA	
}	TokenNameRBRACE	
;	TokenNameSEMICOLON	
}	TokenNameRBRACE	
